# Wildfly server with additional configurations

FROM jboss/wildfly

MAINTAINER Lucas Russo

RUN OPTNAMESERVER
    /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent

# Setup directoties for installing connectors
RUN mkdir -p /opt/jboss/wildfly/modules/org/postgresql/main
