# Wildfly server with additional configurations

FROM jboss/wildfly

MAINTAINER Lucas Russo

# Add our custom configuration
ADD configuration /opt/jboss/wildfly/standalone/configuration/

RUN OPTNAMESERVER
    /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

# Setup directories for installing connectors
RUN mkdir -p /opt/jboss/wildfly/modules/org/postgresql/main
