# Wildfly server with additional configurations

FROM jboss/wildfly:9.0.2.Final

MAINTAINER Lucas Russo

ENV POSTGRES_VERSION_DOWN ENV_POSTGRES_VERSION

# Add our custom configuration
ADD configuration /opt/jboss/wildfly/standalone/configuration/

# User root user to install software
USER root

# Create default admin user
RUN OPTNAMESERVER
    /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

# Switch back to jboss user
USER jboss

# Deploy JDBC Postgres
COPY deploy/postgresql-$POSTGRES_VERSION_DOWN.jar /opt/jboss/wildfly/standalone/deployments/
