#!/usr/bin/env bash

#NET_NAME="postgres"
NET_NAME="dockerrbaccomposed_postgres-rbac"
DNS_IP="10.0.0.72"
WILDFLY_PORT=8080
LOCAL_WILDFLY_PORT=8080
ADMIN_PORT=9990
LOCAL_ADMIN_PORT=9990
POSTGRES_VERSION=9.4.1207
NAMES_VERSION=3.2.5
NAMING_CONVENTION_VERSION=master
ESS_JAVA_CONFIG_VERSION=2.1.1
WAIT_FOR_IT_VERSION=master

ESS_JAVA_CONFIG_REPO=ess-java-config
WAIT_FOR_IT_REPO=wait-for-it

NAMING_CONVENTION_DOCKER_ORG_NAME=lnls
NAMING_CONVENTION_DOCKER_RUN_NAME=naming-service-wildfly
NAMING_CONVENTION_DOCKER_IMAGE_NAME=docker-${NAMING_CONVENTION_DOCKER_RUN_NAME}

DB_NAME=naming-service-postgres
DB_PORT=5432

NAMING_CONVENTION_REPO=naming-convention-tool
NAMING_CONVENTION_TARGET_WAR=${NAMING_CONVENTION_REPO}/NamingConventionTool/target/names-${NAMES_VERSION}.war
NAMING_CONVENTION_TARGET_SIMPLIFIED_WAR=names.war
